sudo: false

language: ruby
rvm:
- 2.5

env:
  global:
  - GH_REF: github.com/Electrical-Age/electrical-age.github.io.git
  - secure: AqIr/bdpfgmotNL+zhbn8CFHXmetV1kXDC/2FkWy5U7axA8TvoOkZiWS03CkTNY1JMqBvIVg3PekZr4RLKB15M4gH19zSRfSoWdByB1OnHHboLkhYeJaen75PXmhFZNu1p2RFR84RNeejVE0bdxykYuDj8fHc1JYnGGt4eXCs9k=

cache: bundler

before_install:
  - gem update --system
  - gem --version
  - gem install bundler

install: bundle install --jobs=3 --retry=3
script: "script/cibuild.sh"

# Only run deploy on develop branch.
# Skipped if not executed on Travis CI or if it is a PR.
deploy:
  skip_cleanup: true
  provider: script
  script: "script/cideploy.sh"
  on:
    branch: develop
