sudo: false

language: ruby
rvm:
- 2.5

env:
  global:
  - GH_REF: github.com/Electrical-Age/electrical-age.github.io.git
  - secure: kNqcJGZ6Z545ULlipXvjvWnekovuJTDx79uvQLAhZI6+6MrLJndJSYYzqBOD6yjI3NxjIckpVmCvTLDFDcS4wlUZ1IrNAk6Nep50MHiIN2qn0yjduxOXDEVeNl88q7ZbwVPMc7gsOyptjrHX4xklhP/ycDTk1ev3JJjI66ECb7U=

cache: bundler

before_install:
  - gem update --system
  - gem --version
  - gem install bundler

install: bundle install --jobs=3 --retry=3
script: "script/cibuild.sh"

# Only run deploy on develop branch.
# Skipped if not executed on Travis CI or if it is a PR.
deploy:
  skip_cleanup: true
  provider: script
  script: "script/cideploy.sh"
  on:
    branch: develop
