# Dependencies
markdown:         redcarpet
highlighter:      pygments

redcarpet:
  extensions: ["smart", "tables"]

kramdown: 
  input: GFM

# Permalinks
relative_permalinks: false
permalink: news/:title/

include: ['_pages']
exclude: ['README.md', 'LICENSE.md', 'Gemfile.lock', 'Gemfile']

# Responsive-image
responsive_image:
  template: _includes/responsive-image.html

  default_quality: 90

  sizes:
    - width: 350   # For low-bandwidth connections.
      quality: 80
    - width: 700   # The size Chrome computes for the carousel.
    - width: 1400  # For Retina screens.

  output_path_format: assets/resized/%{width}/%{basename}


# Collections
collections:


# Setup
title:            'Electrical Age'
description:      'Minecraft mod - Codename : ELN'
url:              https://electrical-age.github.io
enforce_ssl:      electrical-age.github.io
baseurl:          /

# Custom vars
last_version:	  1.10_r50

github:
  repo:           https://github.com/Electrical-Age/electrical-age.github.io
