# Dependencies
markdown:         kramdown

kramdown:
  syntax_highlighter: rouge

gems:
  - jemoji

# Permalinks
relative_permalinks: false
permalink: :title/

include:
  - _pages

exclude:
  - LICENSE.md
  - README.md
  - assets/temp/
  - Gemfile
  - Gemfile.lock
  - script/
  - _pages/blog.html

# Responsive-image
responsive_image:
  template: _includes/responsive-image.html

  default_quality: 90

  sizes:
    - width: 350   # For low-bandwidth connections.
      quality: 80
    - width: 700   # The size Chrome computes for the carousel.
    - width: 1400  # For Retina screens.

  output_path_format: assets/screenshots/%{width}/%{basename}

# Setup
title:         Electrical Age
description:   "Minecraft mod - Codename : ELN"
url:           https://electrical-age.github.io
enforce_ssl:   electrical-age.github.io
baseurl:       ""
analytics_key: UA-49110359-1

# Feed
author:
  name: Electrical-Age Team

github:
  repo:        https://github.com/Electrical-Age/electrical-age.github.io
